#define CAESAR_ADT_EXPERT_T 5.6

/*
 * This file illustrates how to use hash tables to store LOTOS sorts.
 * For a complete explanation, see entry 1250 of file $CADP/HISTORY.
 */

#define CAESAR_ADT_HASH_LIST -7
/*
 * Seven bits are sufficient to encode all the 88 lists generated by the
 * program $CADP/demos/demo_05/user.c
 */
