#! /bin/sh 

###############################################################################
#                       E U C A L Y P T U S - 2
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       cadp_web
#   Auteurs             :       Aldo MAZZILLI, Hubert GARAVEL et
#                               Nicolas DESCOUBES
#   Version             :       1.24
#   Date                :       2017/11/08 14:56:26
##############################################################################

COMMAND=`basename "$0"`
 
ARCH=`"$CADP"/com/arch`

if [ "$NAVIGATOR" = "" ]
then
	case $ARCH in
		sun3 | sun4 | sun5 | sun64 | sol86 | sol64 | iX86 | x64 | ia64 )
			# valeur par defaut
			NAVIGATOR="firefox"

			# On complete le $PATH de maniere plausible
                        PATH="$PATH:/usr/bin:/usr/local/bin:/usr/sfw/bin"
			export PATH

			# recherche d'un navigateur disponible
			for N in firefox netscape mozilla konqueror galeon amaya opera
			do
				WHICH_N=`"$CADP"/src/com/cadp_which "$N"`
				if [ "$WHICH_N" != "$N" ]
				then
					# cadp_which a trouve' le navigateur et
					# renvoye' son chemin d'acces complet
					NAVIGATOR="$N"
					break
				fi
			done
			;;
		win32 )
			NAVIGATOR="iexplore.exe"
			# Sous plusieurs versions de Windows, iexplore.exe 
			# n'est pas dans le $PATH standard: on doit l'y ajouter

			ROOT=`"$CADP"/src/com/cadp_path -root`

			# Pour Windows 98, 2000 Professional, XP et 7
			PATH="$PATH:$ROOT/Program Files/Internet Explorer"
			export PATH
			;;
		macOS | mac86 | mac64 )
			NAVIGATOR="open"
			# c'est la commande "/usr/bin/open" qui se charge de
			# trouver une application capable d'afficher une page
			# Web
			;;
		* )
			echo "$COMMAND: unknown architecture $ARCH"
			exit 1 ;;
	esac
fi

if [ "$1" = "-default" ]
then
	"$CADP"/src/com/cadp_which "$NAVIGATOR"
	exit 0
fi

"$NAVIGATOR" "$@" &

