#! /bin/sh 

###############################################################################
#                       E U C A L Y P T U S - 2
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       cadp_print
#   Auteur              :       Aldo MAZZILLI et Hubert GARAVEL
#   Version             :       1.13
#   Date                :       2018/12/04 10:53:29
##############################################################################

COMMAND=`basename "$0"`
 
ARCH=`"$CADP"/com/arch`

# hypothese: les options passees a ce shell-script respectent les conventions
# de "lpr" 

case $ARCH in
	sun3 | sun4 | iX86 | x64 | ia64 | macOS | mac86 | mac64 )
		# lpr se trouve soit dans /bin, soit dans /usr/bin
		LPR="lpr"
		;;
	sun5 | sun64 | sol86 | sol64 )
		# sous Solaris 10, lpr se trouve soit dans /bin, soit dans
		# /usr/ucb ; sous OpenIndiana, lpr se trouve dans
		# /usr/lib/cups/bin
		PATH="$PATH:/usr/ucb:/usr/lib/cups/bin"
		export PATH
		LPR="lpr"
		;;
	win32 )
		LPR="write.exe /p"
		# sur Windows 2000 et XP, il existe "/WINNT/system32/lpr"
		;;
	* )
		echo "$COMMAND: unknown architecture $ARCH"
		exit 1 ;;
esac

if [ "$1" = "-default" ]
then
	# a terme, il faudrait utiliser $CADP/src/com/cadp_which ici
	if [ "$ARCH" != win32 -a "$PRINTER" != "" ]
	then
		echo "$LPR -P$PRINTER"
	else
		echo "$LPR"
	fi
	exit 0
fi

$LPR "$@"

