#!/bin/sh

###############################################################################
#                               C A D P 
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       cadp_flags
#   Auteurs             :       Hubert Garavel et Wendelin Serwe
#   Version             :       1.4
#   Date                :       2017/11/08 14:55:21
##############################################################################

COMMAND=`basename "$0"`

ARCH=`"$CADP"/com/arch`

# determination des $LDFLAGS requis sur les differentes architectures
# (-lm doit obligatoirement etre present en fin de ligne)

case $ARCH in
	sun5 | sun64 | sol86 | sol64 )
		echo "-lsocket -lnsl -lm"
		;;

	iX86 | x64 | ia64 )
		echo "-lm"
		;;

	win32 )
		# il semble que l'option -lwinmm serve uniquement a Distributor
		# pour lui permettre de trouver la fonction timeGetTime()
		echo "-lwinmm -lm"
		;;

	macOS | mac86 | mac64 )
		echo "-lm"
		;;

	* )
		echo "$COMMAND: unknown architecture '$ARCH'"
		exit 1
		;;
esac
exit 0

