#! /bin/sh

###############################################################################
#                               C A D P 
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       cadp_cpp
#   Auteur              :       Hubert GARAVEL
#   Version             :       1.19
#   Date                :       2017/12/20 18:02:04
##############################################################################

COMMAND=`basename "$0"`
 
DETAILED_ARCH=`"$CADP"/com/arch -detailed`

case $DETAILED_ARCH in
	sun3 | sun4 )
		CADP_CPP="/lib/cpp"
		;;

	sun5 | sun64 | sol86 | sol64 )
		CADP_CPP="/usr/ccs/lib/cpp"
		;;

	iX86 | iX86-64 | x64 | ia64 | macOS | mac86 | mac64 )
		CADP_CPP="/usr/bin/cpp"
		;;

	win32-cygnus | win64-cygnus | win32-msys )
		if [ -x /bin/i686-pc-mingw32-cpp ]
		then
			CADP_CPP="/bin/i686-pc-mingw32-cpp"
		elif [ -x /bin/cpp ]
		then
			CADP_CPP="/bin/cpp"
		else
			# en supposant qu'il existe
			CADP_CPP="/usr/bin/cpp"
		fi
		;;

	* )
		echo "$COMMAND: unknown detailed architecture $DETAILED_ARCH"
		exit 1 ;;
esac

if [ "$1" = "-default" ]
then
        "$CADP"/src/com/cadp_which "$CADP_CPP"
        exit 0
fi
 
"$CADP_CPP" -P "$@" 

