#! /bin/sh 

###############################################################################
#                               C A D P 
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       cadp_rm
#   Auteurs             :       Hubert GARAVEL et Frederic LANG
#   Version             :       1.13
#   Date                :       2017/12/20 18:05:40
##############################################################################

COMMAND=`basename "$0"`
 
DETAILED_ARCH=`"$CADP"/com/arch -detailed`

case $DETAILED_ARCH in
	sun3 | sun4 | sun5 | sun64 | sol86 | sol64 | iX86 | iX86-64 | x64 | ia64 | macOS | mac86 | mac64 )
		rm -f "$@"
		;;

	win32-cygnus | win64-cygnus | win32-msys )
		# Sous Cygwin et Mingw, lorsque l'on veut effacer un programme
		# executable (par exemple "executor"), la commande "rm" echoue
		# parce que le programme s'appelle en realite "executor.exe".
		# C'est pourquoi, on essaie d'abord d'effacer "executor" et,
		# en cas d'echec, on tente d'effacer ensuite "executor.exe"

		for FILE in "$@"
		do
			rm "$FILE" 2> /dev/null || rm -f "$FILE".exe
		done
		;;

	* )
		echo "$COMMAND: unknown detailed architecture $DETAILED_ARCH"
		exit 1 ;;
esac

