#!/bin/sh

###############################################################################
#                       I N S T A L L A T O R
#-----------------------------------------------------------------------------
#   INRIA
#   Unite de Recherche Rhone-Alpes
#   655, avenue de l'Europe
#   38330 Montbonnot Saint Martin
#   FRANCE
#-----------------------------------------------------------------------------
#   Module              :       install_version
#   Auteur              :       Hubert GARAVEL
#   Version             :       1.5
#   Date                :       2012/04/06 12:49:48
##############################################################################

FILE="$1"

RESULT=`(LC_ALL="C" ; export LC_ALL ; grep '^[A-Z]' "$FILE") | "$CADP_INSTALLATOR"/src/com/cadp_tail -n 2`

if test "$RESULT" != ""
then
  echo "$RESULT"
else
  echo "VERSION UNKNOWN"
fi

exit 0
